name: Tests

on: pull_request

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']

    env:
      USE_TRILINOS: 1
      ZOLTAN_INCLUDE: /usr/include/trilinos
      ZOLTAN_LIBRARY: /usr/lib/x86_64-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Linux packages ZOLTAN support
        run: |
          sudo apt-get update
          sudo apt-get install -y openmpi-bin libopenmpi-dev libtrilinos-zoltan-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt
          python setup.py develop
      - name: Run tests
        run: pytest -v pyzoltan
